FROM node:24-alpine AS deps
WORKDIR /app

RUN ["npm", "install", "-g", "pnpm@10.13.1"]

COPY package.json pnpm-lock.yaml ./

RUN ["pnpm", "install", "--frozen-lockfile", "--ignore-scripts"]

FROM deps AS builder
WORKDIR /app

COPY . .
COPY --from=deps /app/node_modules ./node_modules

RUN ["pnpm", "run", "test:generate-output"]
RUN ["pnpm", "run", "build"]

FROM deps AS runner
WORKDIR /app

ENV NODE_ENV production

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

RUN ["addgroup", "--system", "--gid", "1001", "nodejs"]
RUN ["adduser", "--system", "--uid", "1001", "nextjs"]
RUN ["chown", "-R", "nextjs:nodejs", "/app"]
USER nextjs

EXPOSE 3000

CMD ["pnpm", "start"] 